---
# General

# Set hostname
host_name: loken

# User space

# Set user to be used for configuration
username: "{{ lookup('env', 'USER') }}"

# Dotfiles
configure_dotfiles: true
dotfiles_home: "~"
dotfiles_repo_local_destination: "~/user_dotfiles"
dotfiles_repo: "https://github.com/skalarock/dotfiles.git"
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_files:
  - .vimrc
  - .tmux.conf
  - .gitconfig

# Git
git_user_name: Dominik Skalican
git_user_email: dominik.skalican@protonmail.com

# Bash-it
bash_it_repo: https://github.com/Bash-it/bash-it.git
bash_it_dest: ~/.bash_it
bash_it_version: master
bash_it_setup_file: $HOME/Configure_Bash_it

# Install and configure tmux
configure_tmux: true
tmux_dir: $HOME/.tmux

# Install Nerd Fonts
install_fonts: true
installed_nerdfonts:
  - Meslo

# Install flatpak and listed packages
install_flatpak: true
flatpak_packages:
  - org.inkscape.Inkscape
  - org.shotcut.Shotcut
  - org.gimp.GIMP
  - com.obsproject.Studio
  - org.audacityteam.Audacity
  - ch.protonmail.protonmail-bridge
  - com.discordapp.Discord
  - com.github.tchx84.Flatseal
  - com.heroicgameslauncher.hgl
  - com.valvesoftware.Steam
  - io.github.RodZill4.Material-Maker
  - md.obsidian.Obsidian
  - org.blender.Blender
  - org.keepassxc.KeePassXC
  - org.mozilla.Thunderbird
  - org.mozilla.firefox
  - org.signal.Signal
  - org.telegram.desktop
  - org.godotengine.Godot
  - org.kde.krita

# Application packages
packages_to_install:
  - neofetch
  - nano
  - htop
  - youtube-dl
  - bpytop
  - glances
  - tmux
  - git
  - podman
  - skopeo
  - buildah
  - ansible
  - tailscale
  - vagrant
  - vagrant-libvirt
  - tmux
  - nala

# Install PIP packages
pip_packages:
  - name: pip
    state: latest

# Podman configuration
volume_name: LibSQL
