---
- name: Configure host
  hosts: all

  vars_files:
    - example.config.yml

  pre_tasks:
    - name: Include main playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    #- role: petermosmans.customize-gnome
    #  when: configure_gnome
    #  tags: ["gnome"]

  tasks:
    - name: Include hostname configuration
      ansible.builtin.import_tasks:
        file: tasks/hostname.yml
      tags: ["hostname"]

    - name: Include directories task configuration.
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["dirs"]

    - name: Include repositories configuration
      ansible.builtin.import_tasks:
        file: tasks/repositiories.yml
      when: add_repositories
      tags: ["repositories"]

    - name: Include flatpak packages task configuration
      ansible.builtin.import_tasks:
        file: tasks/flatpak.yml
      when: install_flatpak
      tags: ["flatpak"]

    - name: Include tmux task configuration
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      when: configure_tmux
      tags: ["tmux"]

    - name: Include fonts task configuration
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include bash-it task configuration
      ansible.builtin.import_tasks:
        file: tasks/bash_it.yml
      when: install_bash_it
      tags: ["bash_it"]

    - name: Include sudoers task configuration.
      ansible.builtin.import_tasks:
        file: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - name: update cache and upgrade
      apt: update_cache=yes upgrade=safe cache_valid_time=3600

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages_to_install }}"

    - ping:

    - name: Remove dependencies that are not longer required
      apt:
        autoremove: yes
