---
- name: Configure host
  hosts: all

  vars_files:
    - example.config.yml

  pre_tasks:
    - name: Include main playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]

  tasks:
    - name: Include hostname configuration
      ansible.builtin.import_tasks:
        file: tasks/hostname.yml
      tags: ["hostname"]

    - name: Include directories task configuration.
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["dirs"]

    - name: Include repositories configuration
      ansible.builtin.import_tasks:
        file: tasks/repositories.yml
      when: add_repositories
      tags: ["repositories"]

    - name: Include packages configuration
      ansible.builtin.import_tasks:
        file: tasks/packages.yml
      when: add_packages
      tags: ["packages"]

    - name: Include flatpak packages task configuration
      ansible.builtin.import_tasks:
        file: tasks/flatpak.yml
      when: install_flatpak
      tags: ["flatpak"]

    - name: Include tmux task configuration
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      when: configure_tmux
      tags: ["tmux"]

    - name: Include fonts task configuration
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include bash-it task configuration
      ansible.builtin.import_tasks:
        file: tasks/bash_it.yml
      when: install_bash_it
      tags: ["bash_it"]

    - name: Include sudoers task configuration.
      ansible.builtin.import_tasks:
        file: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]
