- name: Create podman pod
  containers.podman.podman_pod:
    name: learn-sql
    state: started
    ports:
      - "9876:80"
      - "5432:5432"

- name: Create podman volume
  containers.podman.podman_volume:
    state: present
    name: "{{ volume_name }}"
    options:
      - "device=~/home/$USER/"
